# NumPy Reshape/Sort + Pandas `.loc` and `dtype` Practice

Practice notebook while learning NumPy and Pandas.

Covers:
- Reshaping a flat list into a 2D NumPy array
- Sorting descending using `np.sort()` + reverse slicing (`[::-1]`), no manual loop
- Converting a dict into a Pandas DataFrame
- Row lookup using `.loc` (label-based indexing)
- Difference between `type(df["col"])` (always `Series`) and `df["col"].dtype` (actual data type stored, e.g. `object` for text)

In [ ]:
import numpy as np
import pandas as pd

SCORES = [45, 60, 12, 89, 34, 77, 5, 99]
SQUAD = {"player": ["Rohit", "Kohli", "Bumrah"], "role": ["Batter", "Batter", "Bowler"]}
ROW_INDEX = 1

def build_score_grid(scores):
    df = np.array(scores).reshape(2, 4)
    sorted_desc = np.sort(scores)[::-1]
    return df, sorted_desc

def build_squad_lookup(squad, row_index):
    df = pd.DataFrame(squad)
    # Testing whether .loc works on a numpy array — spoiler: it doesn't. np.array() has no .loc,
    # only a pandas DataFrame does. That's why we build a DataFrame here instead.
    row1 = df.loc[row_index]
    return row1, df["player"].dtype

if __name__ == "__main__":
    grid, desc_grid = build_score_grid(SCORES)
    print("Reshaped scores:")
    print(grid)
    print("descending order:")
    print(desc_grid)

    row, player_dtype = build_squad_lookup(SQUAD, ROW_INDEX)
    print("\nRow at index", ROW_INDEX, ":")
    print(row)
    print('\nColumn dtype for "player":', player_dtype)

### Expected output
```
Reshaped scores:
[[45 60 12 89]
 [34 77  5 99]]
descending order:
[99 89 77 60 45 34 12  5]

Row at index 1 :
player     Kohli
role      Batter
Name: 1, dtype: object

Column dtype for "player": object
```

### Key takeaways
- `np.sort()` only sorts ascending — reverse it with `[::-1]` slicing instead of writing a manual descending sort.
- `.loc` is a pandas-only feature (label-based row/column access). Plain NumPy arrays don't have it — only positional `[]` indexing.
- `type(df["col"])` always returns `Series` (the container type). `df["col"].dtype` returns what's actually *stored inside* the column — `object` for pandas text columns, since pandas keeps strings as generic Python objects rather than a dedicated string dtype by default.